# Generated by Django 2.1.5 on 2019-01-25 17:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_reg', models.CharField(max_length=50)),
                ('nom_prov', models.CharField(max_length=20)),
                ('nom_com', models.CharField(max_length=30)),
                ('shape_leng', models.FloatField()),
                ('dis_elec', models.IntegerField()),
                ('cir_sena', models.IntegerField()),
                ('cod_comuna', models.IntegerField()),
                ('shape_le_1', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
